user:
  jay:
    username: 周杰伦
    password: 1234abcd!
  william:
    username: william
    password: 1234abcd!
  chen:
    username: william
    password: william!



url: http://192.168.3.92

mysql:
  db: trading_system
  host: 192.168.3.92
  password: william
  port: 3306
  user: root